/****** Object:  Table [dbo].[StockForums]    Script Date: 2017/7/3 ¤U¤È 09:12:15 ******/
DROP TABLE IF EXISTS [dbo].[StockForums]
GO

/****** Object:  Table [dbo].[StockForums]    Script Date: 2017/7/3 ¤U¤È 09:12:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[StockForums](
	[ID] BIGINT NOT NULL IDENTITY(1,1),
	[Source] VARCHAR(10) NOT NULL,
	[Subject] NVARCHAR(50) NOT NULL,
	[Meta] NVARCHAR(500) NOT NULL,
	[Url] VARCHAR(200) NOT NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT (GETDATE()),
 CONSTRAINT [PK_StockForums] PRIMARY KEY CLUSTERED 
(
	[ID] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
