/****** Object:  Index [IX_StockForums_Hash]    Script Date: 2021/1/6 ¤U¤È 10:39:52 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_StockForums_Hash] ON [dbo].[StockForums]
(
	[Hash] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


