<?xml version="1.0" encoding="utf-8"?><Database Name="Stock" Class="StockDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=Stock;Integrated Security=True" SettingsObjectName="StockCrawler.Dao.Properties.Settings" SettingsPropertyName="StockConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="dbo.DeleteStockPriceHistoryData" Method="DeleteStockPriceHistoryData">
    <Parameter Name="pStockNo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="pTradeDate" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertOrUpdateStockReportMonthlyNetProfitTaxed" Method="InsertOrUpdateStockReportMonthlyNetProfitTaxed">
    <Parameter Name="pStockNo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="pYear" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="pMonth" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="pNetProfitTaxed" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pLastYearNetProfitTaxed" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pDelta" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pDeltaPercent" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="pThisYearTillThisMonth" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pLastYearTillThisMonth" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pTillThisMonthDelta" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pTillThisMonthDeltaPercent" Type="System.Decimal" DbType="Decimal(18,4)" />
    <Parameter Name="pRemark" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="pPE" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DisableAllStocks" Method="DisableAllStocks">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetStockBasicInfo" Method="GetStockBasicInfo">
    <Parameter Name="pStockNo" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="GetStockBasicInfoResult">
      <Column Name="StockName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StockNo" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyID" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BuildDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="PublishDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Capital" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="MarketValue" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ReleaseStockCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Chairman" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CEO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Business" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStockPeriodPrice" Method="GetStockPeriodPrice">
    <Parameter Name="pStockNo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="pEndDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="pPeriod" Type="System.Int16" DbType="SmallInt" />
    <ElementType Name="GetStockPeriodPriceResult">
      <Column Name="StockNo" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="StockDT" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Period" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="OpenPrice" Type="System.Decimal" DbType="Decimal(10,4) NOT NULL" CanBeNull="false" />
      <Column Name="HighPrice" Type="System.Decimal" DbType="Decimal(10,4) NOT NULL" CanBeNull="false" />
      <Column Name="LowPrice" Type="System.Decimal" DbType="Decimal(10,4) NOT NULL" CanBeNull="false" />
      <Column Name="ClosePrice" Type="System.Decimal" DbType="Decimal(10,4) NOT NULL" CanBeNull="false" />
      <Column Name="AdjClosePrice" Type="System.Decimal" DbType="Decimal(10,4) NOT NULL" CanBeNull="false" />
      <Column Name="Volume" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStockPriceAVG" Method="GetStockPriceAVG">
    <Parameter Name="pStockNo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="pDateEnd" Type="System.DateTime" DbType="Date" />
    <Parameter Name="pPeriod" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="oAvgClosePrice" Type="System.Decimal" DbType="Money" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetStockPriceHistory" Method="GetStockPriceHistory">
    <Parameter Name="pStockNo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="pDateBegin" Type="System.DateTime" DbType="Date" />
    <Parameter Name="pDateEnd" Type="System.DateTime" DbType="Date" />
    <Parameter Name="pPeriod" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="pTop" Type="System.Int32" DbType="Int" />
    <Parameter Name="pCurrentPage" Type="System.Int32" DbType="Int" />
    <Parameter Name="pPageSize" Type="System.Int32" DbType="Int" />
    <Parameter Name="oPageCount" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="GetStockPriceHistoryResult">
      <Column Name="StockNo" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="StockDT" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Period" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="OpenPrice" Type="System.Decimal" DbType="Decimal(10,4) NOT NULL" CanBeNull="false" />
      <Column Name="HighPrice" Type="System.Decimal" DbType="Decimal(10,4) NOT NULL" CanBeNull="false" />
      <Column Name="LowPrice" Type="System.Decimal" DbType="Decimal(10,4) NOT NULL" CanBeNull="false" />
      <Column Name="ClosePrice" Type="System.Decimal" DbType="Decimal(10,4) NOT NULL" CanBeNull="false" />
      <Column Name="AdjClosePrice" Type="System.Decimal" DbType="Decimal(10,4) NOT NULL" CanBeNull="false" />
      <Column Name="Volume" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="RNO" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStockReportBalance" Method="GetStockReportBalance">
    <Parameter Name="pStockNo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="pYear" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="pSeason" Type="System.Int16" DbType="SmallInt" />
    <ElementType Name="GetStockReportBalanceResult">
      <Column Name="StockName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StockNo" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="StockName1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Enable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="StockNo1" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Season" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CashAndEquivalents" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ShortInvestments" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="BillsReceivable" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Stock" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="OtherCurrentAssets" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="CurrentAssets" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="LongInvestment" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="FixedAssets" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="OtherAssets" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="TotalAssets" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ShortLoan" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ShortBillsPayable" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="AccountsAndBillsPayable" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="AdvenceReceipt" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="LongLiabilitiesWithinOneYear" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="OtherCurrentLiabilities" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="CurrentLiabilities" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="LongLiabilities" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="OtherLiabilities" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="TotalLiability" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="NetWorth" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="NAV" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt1" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedAt1" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStockReportCashFlow" Method="GetStockReportCashFlow">
    <Parameter Name="pStockNo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="pYear" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="pSeason" Type="System.Int16" DbType="SmallInt" />
    <ElementType Name="GetStockReportCashFlowResult">
      <Column Name="StockName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StockNo" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Season" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Depreciation" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="AmortizationFee" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="BusinessCashflow" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="InvestmentCashflow" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="FinancingCashflow" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="CapitalExpenditures" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="FreeCashflow" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="NetCashflow" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStockReportIncome" Method="GetStockReportIncome">
    <Parameter Name="pStockNo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="pYear" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="pSeason" Type="System.Int16" DbType="SmallInt" />
    <ElementType Name="GetStockReportIncomeResult">
      <Column Name="StockName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StockNo" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Season" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Revenue" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="GrossProfit" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="SalesExpense" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ManagementCost" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="RDExpense" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="OperatingExpenses" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="BusinessInterest" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="NetProfitTaxFree" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="NetProfitTaxed" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="EPS" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="SEPS" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ReleaseStockCount" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStockReportMonthlyNetProfitTaxed" Method="GetStockReportMonthlyNetProfitTaxed">
    <Parameter Name="pStockNo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="pYear" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="pMonth" Type="System.Int16" DbType="SmallInt" />
    <ElementType Name="GetStockReportMonthlyNetProfitTaxedResult">
      <Column Name="StockName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StockNo" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="StockName1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Enable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="StockNo1" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Month" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="NetProfitTaxed" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="LastYearNetProfitTaxed" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Delta" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="DeltaPercent" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="ThisYearTillThisMonth" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="LastYearTillThisMonth" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="TillThisMonthDelta" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="TillThisMonthDeltaPercent" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="PE" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt1" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedAt1" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetStocks" Method="GetStocks">
    <ElementType Name="GetStocksResult">
      <Column Name="StockNo" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="StockName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Enable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertOrUpdateStock" Method="InsertOrUpdateStock">
    <Parameter Name="pStockNo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="pStockName" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertOrUpdateStockBasicInfo" Method="InsertOrUpdateStockBasicInfo">
    <Parameter Name="pStockNo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="pCategory" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="pCompanyName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="pCompanyID" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="pBuildDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="pPublishDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="pCapital" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pMarketValue" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pReleaseStockCount" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="pChairman" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="pCEO" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="pUrl" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="pBusiness" Type="System.String" DbType="NVarChar(1000)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertOrUpdateStockPriceHistory" Method="InsertOrUpdateStockPriceHistory">
    <Parameter Name="pStockNo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="pStockDT" Type="System.DateTime" DbType="Date" />
    <Parameter Name="pPeriod" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="pOpenPrice" Type="System.Decimal" DbType="Decimal(10,4)" />
    <Parameter Name="pHighPrice" Type="System.Decimal" DbType="Decimal(10,4)" />
    <Parameter Name="pLowPrice" Type="System.Decimal" DbType="Decimal(10,4)" />
    <Parameter Name="pClosePrice" Type="System.Decimal" DbType="Decimal(10,4)" />
    <Parameter Name="pVolume" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="pAdjClosePrice" Type="System.Decimal" DbType="Decimal(10,4)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertOrUpdateStockReportBalance" Method="InsertOrUpdateStockReportBalance">
    <Parameter Name="pStockNo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="pYear" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="pSeason" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="pCashAndEquivalents" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pShortInvestments" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pBillsReceivable" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pStock" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pOtherCurrentAssets" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pCurrentAssets" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pLongInvestment" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pFixedAssets" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pOtherAssets" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pTotalAssets" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pShortLoan" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pShortBillsPayable" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pAccountsAndBillsPayable" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pAdvenceReceipt" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pLongLiabilitiesWithinOneYear" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pOtherCurrentLiabilities" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pCurrentLiabilities" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pLongLiabilities" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pOtherLiabilities" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pTotalLiability" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pNetWorth" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertOrUpdateStockReportCashFlow" Method="InsertOrUpdateStockReportCashFlow">
    <Parameter Name="pStockNo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="pYear" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="pSeason" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="pDepreciation" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pAmortizationFee" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pBusinessCashflow" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pInvestmentCashflow" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pFinancingCashflow" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pCapitalExpenditures" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pFreeCashflow" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pNetCashflow" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertOrUpdateStockReportIncome" Method="InsertOrUpdateStockReportIncome">
    <Parameter Name="pStockNo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="pYear" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="pSeason" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="pRevenue" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pGrossProfit" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pSalesExpense" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pManagementCost" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pRDExpense" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pOperatingExpenses" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pBusinessInterest" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pNetProfitTaxFree" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pNetProfitTaxed" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pEPS" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pSEPS" Type="System.Decimal" DbType="Money" />
    <Parameter Name="pRelaseStockCount" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
</Database>