<?xml version="1.0" encoding="utf-8"?><Database Name="Stock" Class="StockDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=Stock;Integrated Security=True" SettingsObjectName="StockCrawler.Dao.Properties.Settings" SettingsPropertyName="StockConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="dbo.DeleteStockPriceHistoryData" Method="DeleteStockPriceHistoryData">
    <Parameter Name="pStockID" Type="System.Int32" DbType="Int" />
    <Parameter Name="pTradeDate" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertStockPriceHistoryData" Method="InsertStockPriceHistoryData">
    <Parameter Name="pStockID" Type="System.Int32" DbType="Int" />
    <Parameter Name="pStockDT" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="pOpenPrice" Type="System.Decimal" DbType="Decimal(10,4)" />
    <Parameter Name="pHighPrice" Type="System.Decimal" DbType="Decimal(10,4)" />
    <Parameter Name="pLowPrice" Type="System.Decimal" DbType="Decimal(10,4)" />
    <Parameter Name="pClosePrice" Type="System.Decimal" DbType="Decimal(10,4)" />
    <Parameter Name="pVolume" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="pAdjClosePrice" Type="System.Decimal" DbType="Decimal(10,4)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DisableAllStocks" Method="DisableAllStocks">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetStocks" Method="GetStocks">
    <ElementType Name="GetStocksResult">
      <Column Name="StockID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StockNo" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="StockName" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Enable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertOrUpdateStockList" Method="InsertOrUpdateStockList">
    <Parameter Name="pStockNo" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="pStockName" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>